src/Entity/Gradja.php
<?php

namespace App\Entity;

use App\Repository\GradjaRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=GradjaRepository::class)
 */
class Gradja
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Isbn
     */
    private ?string $ISBN;

    /**
     * @ORM\Column(type="string", length=512)
     * @Assert\NotBlank
     */
    private ?string $naslov;

    /**
     * @ORM\Column(type="string", length=2048, nullable=true)
     *
     */
    private ?string $fotografija;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $opis;

    /**
     * @ORM\Column(type="date")
     *
     */
    private ?DateTimeInterface $datumDodavanja;


    /**
     * @ORM\Column(type="date", nullable=true)
     *
     */
    private ?DateTimeInterface $godinaIzdanja;

    /**
     * @ORM\Column(type="string", length=191, unique=true)
     *
     */
    private $brojInventara;

    /**
     * @ORM\ManyToMany(targetEntity=Autori::class, inversedBy="popisGradje")
     */
    private $autori;

    /**
     * @ORM\ManyToOne(targetEntity=Statusi::class, inversedBy="gradje")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Statusi $status;

    /**
     * @ORM\ManyToMany(targetEntity=Zanrovi::class, inversedBy="gradje")
     */
    private $zanrovi;

    /**
     * @ORM\ManyToOne(targetEntity=Knjiznice::class, inversedBy="gradje")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Knjiznice $knjiznicaVlasnik;

    /**
     * @ORM\OneToMany(targetEntity=Posudbe::class, mappedBy="gradja")
     */
    private $posudbe;

    /**
     * @ORM\ManyToOne(targetEntity=Izdavaci::class, inversedBy="gradje")
     */
    private ?Izdavaci $izdavac;

    /**
     * @ORM\ManyToOne(targetEntity=Jezici::class, inversedBy="gradje")
     */
    private ?Jezici $jezici;

    public function __construct()
    {
        $this->autori = new ArrayCollection();
        $this->zanrovi = new ArrayCollection();
        $this->posudbe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getISBN(): ?string
    {
        return $this->ISBN;
    }

    public function setISBN(?string $ISBN): self
    {
        $this->ISBN = $ISBN;

        return $this;
    }

    public function getNaslov(): ?string
    {
        return $this->naslov;
    }

    public function setNaslov(string $naslov): self
    {
        $this->naslov = $naslov;

        return $this;
    }

    public function getFotografija(): ?string
    {
        return $this->fotografija;
    }

    public function setFotografija(string $fotografija): self
    {
        $this->fotografija = $fotografija;

        return $this;
    }

    public function getOpis(): ?string
    {
        return $this->opis;
    }

    public function setOpis(?string $opis): self
    {
        $this->opis = $opis;

        return $this;
    }

    public function getDatumDodavanja(): ?DateTimeInterface
    {
        return $this->datumDodavanja;
    }

    public function setDatumDodavanja(DateTimeInterface $datumDodavanja): self
    {
        $this->datumDodavanja = $datumDodavanja;

        return $this;
    }


    public function getGodinaIzdanja(): ?DateTimeInterface
    {
        return $this->godinaIzdanja;
    }

    public function setGodinaIzdanja(?DateTimeInterface $godinaIzdanja): self
    {
        $this->godinaIzdanja = $godinaIzdanja;

        return $this;
    }

    public function getBrojInventara(): ?string
    {
        return $this->brojInventara;
    }

    public function setBrojInventara(string $brojInventara): self
    {
        $this->brojInventara = $brojInventara;

        return $this;
    }

    /**
     * @return Collection|Autori[]
     */
    public function getAutori(): Collection
    {
        return $this->autori;
    }

    public function addAutori(Autori $autori): self
    {
        if (!$this->autori->contains($autori)) {
            $this->autori[] = $autori;
        }

        return $this;
    }

    public function removeAutori(Autori $autori): self
    {
        $this->autori->removeElement($autori);

        return $this;
    }

    public function getStatus(): ?Statusi
    {
        return $this->status;
    }

    public function setStatus(?Statusi $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|Zanrovi[]
     */
    public function getZanrovi(): Collection
    {
        return $this->zanrovi;
    }

    public function addZanrovi(Zanrovi $zanrovi): self
    {
        if (!$this->zanrovi->contains($zanrovi)) {
            $this->zanrovi[] = $zanrovi;
        }

        return $this;
    }

    public function removeZanrovi(Zanrovi $zanrovi): self
    {
        $this->zanrovi->removeElement($zanrovi);

        return $this;
    }

    public function getKnjiznicaVlasnik(): ?Knjiznice
    {
        return $this->knjiznicaVlasnik;
    }

    public function setKnjiznicaVlasnik(?Knjiznice $knjiznicaVlasnik): self
    {
        $this->knjiznicaVlasnik = $knjiznicaVlasnik;

        return $this;
    }

    /**
     * @return Collection|Posudbe[]
     */
    public function getPosudbe(): Collection
    {
        return $this->posudbe;
    }

    public function addPosudbe(Posudbe $posudbe): self
    {
        if (!$this->posudbe->contains($posudbe)) {
            $this->posudbe[] = $posudbe;
            $posudbe->setGradja($this);
        }

        return $this;
    }

    public function removePosudbe(Posudbe $posudbe): self
    {
        if ($this->posudbe->removeElement($posudbe)) {
            // set the owning side to null (unless already changed)
            if ($posudbe->getGradja() === $this) {
                $posudbe->setGradja(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->getNaslov();
    }

    public function getIzdavac(): ?Izdavaci
    {
        return $this->izdavac;
    }

    public function setIzdavac(?Izdavaci $izdavac): self
    {
        $this->izdavac = $izdavac;

        return $this;
    }

    public function getJezici(): ?Jezici
    {
        return $this->jezici;
    }

    public function setJezici(?Jezici $jezici): self
    {
        $this->jezici = $jezici;

        return $this;
    }
}

templates/knjiznicniProfil/knjiznicaPocetna.html.twig
{% extends 'base.html.twig' %}

{% block title %}Izbornik{% endblock %}

{% block body %}
    <div class="korisnik-main knjiznica-main">
        <div class="container">
            <div class="row">
                <div class="grade grade-knjiznica" style="margin-top: 20px;">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/rezervacije.png">
                        <a class="pregled-knjiznica" href="{{ path('rezervacije_korisnika') }}">PREGLED REZERVACIJA</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grade grade-knjiznica">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/posudbe.png">
                        <a class="pregled-knjiznica"  href="{{ path('posudbe_korisnika') }}">PREGLED POSUDBI</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grade grade-knjiznica">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/korisnici1.png">
                        <a class="pregled-knjiznica"  href="{{ path('korisnici_index') }}">PREGLED KORISNIKA</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grade grade-knjiznica">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/popis.png">
                        <a class="pregled-knjiznica"  href="{{ path('gradja_index') }}">PREGLED KNJIGA</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grade grade-knjiznica">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/pisci.png">
                        <a class="pregled-knjiznica"  href="{{ path('autori_index') }}">PREGLED AUTORA</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grade grade-knjiznica">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/jezik.png">
                        <a class="pregled-knjiznica"  href="{{ path('jezici_index') }}">PREGLED JEZIKA</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="grade grade-knjiznica" style="margin-bottom: 30px;">
                    <div class="grada grada-knjiznica">
                        <img class="pregled-slike" src="/files/pitcures/icons/izdavac.png">
                        <a class="pregled-knjiznica"  href="{{ path('izdavaci_index') }}">PREGLED IZDAVAČA</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

templates/knjiznicniProfil/posudjene.html.twig
{% extends 'base.html.twig' %}

{% block title %}Popis posudbi{% endblock %}

{% block nazivTrenutneStraniceKnjiznice %}
    <img src="/files/pitcures/icons/posudenoIcon.png">
    <h1>POPIS POSUDBI</h1>
{% endblock %}

{% block body %}

    <div class="postavke">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">ISBN</th>
                    <th scope="col">Broj inventara</th>
                    <th scope="col">Broj iskaznice korisnika</th>
                    <th scope="col">Datum posudbe</th>
                    <th scope="col">Rok vraćanja</th>
                    <th scope="col">Zakasnina</th>
                    <th scope="col">Opcije</th>
                </tr>
                </thead>
                <tbody>
                {% for posudbe in posudbes %}
                    <tr>
                        <td>{{ posudbe.id }}</td>
                        <td><img src="data:image/png;base64,{{ code.makeBarcode(  posudbe.gradja.iSBN  , "Isbn", "#D1FDFE").generate }}"
                                 alt="Isbn: {{ posudbe.gradja.iSBN  }}"/></td>
                        <td><img src="data:image/png;base64,{{ code.makeBarcode(  posudbe.gradja.brojInventara  , "Code128", "#D1FDFE").generate }}"
                                 alt="Broj inventara: {{ posudbe.gradja.brojInventara  }}"/></td>
                        <td><img src="data:image/png;base64,{{ code.makeBarcode(  posudbe.korisnici.brojIskazniceKorisnika  , "Code39", "#D1FDFE").generate }}"
                                 alt="Broj iskaznice korisnika: {{ posudbe.korisnici.brojIskazniceKorisnika  }}"/></td>
                        <td>{{ posudbe.datumPosudbe ? posudbe.datumPosudbe|date('d.m.Y.') : '' }}</td>
                        <td>{{ posudbe.datumRokaVracanja ? posudbe.datumRokaVracanja|date('d.m.Y.') : '' }}</td>
                        <td>{{ posudbe.zakasnina }} kn</td>
                        <td>
                            <a href="{{ path('vrati_gradju', {'id': posudbe.id}) }}">
                                <button class="knjiznice-btn btn">
                                    Vraćanje
                                </button>
                            </a>
                            {% if posudbe.status.id == 9 %}
                                <a href="{{ path('odobri-produljenje', {'id': posudbe.id}) }}">
                                    <button class="btn knjiznice-btn">
                                        Odobri zahtjev za produljenje
                                    </button>
                                </a>
                                <a href="{{ path('odbij-produljenje', {'id': posudbe.id}) }}">
                                    <button class="btn knjiznice-btn">
                                        Odbij zahtjev za produljenje
                                    </button>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="8">nema podataka.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

templates/knjiznicniProfil/rezervirane.html.twig
{% extends 'base.html.twig' %}

{% block title %}Popis rezervacija{% endblock %}

{% block nazivTrenutneStraniceKnjiznice %}
    <img src="/files/pitcures/icons/rezerviranoIcon.png">
    <h1>POPIS REZERVACIJA</h1>
{% endblock %}

{% block body %}
    <div class="postavke">
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>ISBN</th>
                    <th>Broj inventara</th>
                    <th>Broj iskaznice korisnika</th>
                    <th>Datum rezerviranja</th>
                    <th>Datum roka rezervacije</th>
                    <th>Opcije</th>
                </tr>
                </thead>
                <tbody>
                {% for posudbe in posudbes %}
                    <tr>
                        <td>{{ posudbe.id }}</td>
                        <td><img src="data:image/png;base64,{{ code.makeBarcode(  posudbe.gradja.iSBN  , "Isbn", "#D1FDFE").generate }}"
                                 alt="Isbn: {{ posudbe.gradja.iSBN  }}"/></td>
                        <td><img src="data:image/png;base64,{{ code.makeBarcode(  posudbe.gradja.brojInventara  , "Code128", "#D1FDFE").generate }}"
                                 alt="Broj inventara: {{ posudbe.gradja.brojInventara  }}"/></td>
                        <td><img src="data:image/png;base64,{{ code.makeBarcode(  posudbe.korisnici.brojIskazniceKorisnika  , "Code39", "#D1FDFE").generate }}"
                                 alt="Broj iskaznice korisnika: {{ posudbe.korisnici.brojIskazniceKorisnika  }}"/></td>
                        <td>{{ posudbe.datumPosudbe ? posudbe.datumPosudbe|date('d.m.Y.') : '' }}</td>
                        <td>{{ posudbe.datumRokaVracanja ? posudbe.datumRokaVracanja|date('d.m.Y.') : '' }}</td>
                        <td>
                            <button class="btn knjiznice-btn"><a href="{{ path('rezervacija_cancel', {'id': posudbe.id}) }}">Otkaži</a></button>
                            <button class="btn"><a href="{{ path('posudi_rezerviranu_gradju', {'id': posudbe.id}) }}">Posudi</a></button>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="7">nema podataka.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



{% endblock %}